eShop.WebUI/Controllers/AccountingController.cs
using eshop.ApplicationService.CRM;
using eshop.ApplicationService.MasterSetUp;
using eShop.ApplicationService.Account;
using eShop.BusinessDomain.CRM.DomainObject;
using eShop.BusinessDomain.CRM.ViewModels;
using eShop.Infrastructure.Data.UnitOfWork;
using Infrastructure.Crosscutting.Utility;
using Microsoft.Reporting.WinForms;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eShop.WebUI.Controllers
{
  
    public class AccountingController : Controller
    {
        TransectionHistoryService transectionHistoryService = new TransectionHistoryService();
        // GET: Accounting
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AccountCreate()
        {
            return View();
        }
        public ActionResult AccountPayment(int Id=0)
        {
            ViewBag.Id = Id;
            return View();
        }
        public ActionResult AccountReceipt(int Id = 0)
        {
            ViewBag.Id = Id;
            return View();
        }
        public ActionResult AccountManagement()
        {
            return View();
        }
        public ActionResult AccountPayable()
        {
            return View();
        }
        public ActionResult AccountRecive()
        {
            return View();
        }
        public ActionResult CustomerReciveable()
        {
            return View();
        }
        public ActionResult AccountRecivePayment()
        {
            return View();
        }
        public ActionResult AccountTransaction(int Id = 0)
        {
            ViewBag.Id = Id;
            return View();
        }
        //public FileResult Invoice(int Id)
        //{
        //    ReportViewer rptViewer = new ReportViewer();
        //    var data = saleService.GetProductDetail((int)Id);
        //    var org = this.organizationService.GetAllOrganization();
        //    rptViewer.ProcessingMode = ProcessingMode.Local;
        //    rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/eShop.Infrastructure.RDLC/rptInvoiceSalesPos.rdlc");
        //    //rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptInvoiceSalesPos.rdlc");
        //    rptViewer.LocalReport.EnableExternalImages = true;
        //    rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
        //    rptViewer.LocalReport.DataSources.Add(new ReportDataSource("OrgResults", org));
        //    rptViewer.LocalReport.Refresh();
        //    Warning[] warnings;
        //    string[] streamIds;
        //    string mimeType = string.Empty;
        //    string encoding = string.Empty;
        //    string extension = string.Empty;
        //    byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
        //    return File(bytes, "application/pdf");
        //    //return File(bytes, "application/vnd.ms-word", "Report.doc");
        //}
        [HttpGet]
        public FileResult AccountMonthDaily(StockReportVM selseReportVM)
        {
            ReportViewer rptViewer = new ReportViewer();

            var data = transectionHistoryService.GetAllTransectionHistory();
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptStockReport.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
        }
    }
}

eShop.WebUI/Controllers/PurcheaseController.cs
using eshop.ApplicationService.CRM;
using eshop.ApplicationService.MasterSetUp;
using eShop.BusinessDomain.CRM.ViewModels;
using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eShop.WebUI.Controllers
{
    public class PurcheaseController : Controller
    {
        // GET: Purchease
        PurchaseService PurchaseService;
        PurchaseReturnService purchaseReturnService;
        OrganizationService organizationService;
        public PurcheaseController()
        {
            this.PurchaseService = new PurchaseService();
            this.organizationService = new OrganizationService();
            this.purchaseReturnService = new PurchaseReturnService();
        }
        public ActionResult Index()
        {
            return View();


        }
        public ActionResult PurcheasePos(int Id=0)
        {
            ViewBag.Id = Id;
            return View();
        }
        public ActionResult PurcheasePos2(int Id = 0)
        {
            ViewBag.Id = Id;
            return View();
        }
        public ActionResult Purchease() => View();
        public ActionResult PurcheaseList() => View();
        public ActionResult PurcheaseReport() => View();
        [HttpPost]
        public FileResult PurcheaseReport(PurchaseReportVM purchase)
        {

            ReportViewer rptViewer = new ReportViewer();

            var data = this.PurchaseService.PerchesReport(purchase);

            rptViewer.ProcessingMode = ProcessingMode.Local;

            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptPurchaseReport.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
        }
        public ActionResult PurcheaseReturn() => View();
        public ActionResult PurcheaseReturnList() => View();
        public ActionResult PurcheaseReturnReport() => View();
        public FileResult Invoice(int Id)
        {
            ReportViewer rptViewer = new ReportViewer();
            var data = PurchaseService.GetProductDetail((int)Id);
            var org = this.organizationService.GetAllOrganization();
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptInvoicePurchease.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("OrgResults", org));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
            //return File(bytes, "application/vnd.ms-excel", "Report.xls");
            //return File(bytes, "application/vnd.ms-word", "Report.doc");
        }
        public FileResult InvoiceReturn(int Id)
        {
            ReportViewer rptViewer = new ReportViewer();
            var data = purchaseReturnService.GetProductDetail((int)Id);
            var org = this.organizationService.GetAllOrganization();
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptInvoicePurcheaseReturn.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("OrgResults", org));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
            //return File(bytes, "application/vnd.ms-excel", "Report.xls");
            //return File(bytes, "application/vnd.ms-word", "Report.doc");
        }
    }
}

eShop.WebUI/Controllers/SalesController.cs
using eshop.ApplicationService.CRM;
using eshop.ApplicationService.MasterSetUp;
using eShop.BusinessDomain.CRM.ViewModels;
using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace eShop.WebUI.Controllers
{
    public class SalesController : Controller
    {
        SaleService saleService;
        OrganizationService organizationService;
        public SalesController()
        {
            this.saleService = new SaleService();
            this.organizationService = new OrganizationService();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SalesPos(int Id = 0)
        {
            ViewBag.Id = Id;
            return View();
        }
        public ActionResult SalesReturn()
        {
            return View();
        }
        public ActionResult SalesReturnList()
        {
            return View();
        }
        public ActionResult SalesList()
        {
          
            return View();
        }
        public ActionResult Salesreport()
        {
            return View();
        }
        public FileResult Invoice(int Id)
        {
            ReportViewer rptViewer = new ReportViewer();
            var data = saleService.GetProductDetail((int)Id);
            var org = this.organizationService.GetAllOrganization();
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/eShop.Infrastructure.RDLC/rptInvoiceSalesPos.rdlc");
            //rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptInvoiceSalesPos.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("OrgResults", org));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
            //return File(bytes, "application/vnd.ms-word", "Report.doc");
        }
        public FileResult Invoice1(int Id)
        {
            ReportViewer rptViewer = new ReportViewer();
            var data = saleService.GetProductDetail((int)Id);
            var org = this.organizationService.GetAllOrganization();
            rptViewer.ProcessingMode = ProcessingMode.Local;
            //rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/eShop.Infrastructure.RDLC/rptInvoiceSalesPos.rdlc");
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptInvoiceSalesPos.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("OrgResults", org));
            rptViewer.LocalReport.Refresh();

            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
            //return File(bytes, "application/vnd.ms-word", "Report.doc");
        }
        public FileResult Invoicereturn(int Id)
        {
            ReportViewer rptViewer = new ReportViewer();
            var data = saleService.GetProductDetail((int)Id);
            var org = this.organizationService.GetAllOrganization();
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptInvoiceSalesPos.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("OrgResults", org));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
            //return File(bytes, "application/vnd.ms-word", "Report.doc");
        }
        public ActionResult SalseReport()
        {
            return View();
        }
        [HttpPost]
        public FileResult SalseReportCall(SelseReportVM selseReportVM)
        {
            ReportViewer rptViewer = new ReportViewer();

            var data = saleService.GetSalesReportData(selseReportVM);
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptSalseReport.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
        }
    }
}

eShop.WebUI/Controllers/StockController.cs
using eshop.ApplicationService.CRM;
using eShop.BusinessDomain.CRM.ViewModels;
using Microsoft.Reporting.WinForms;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eShop.WebUI.Controllers
{
    public class StockController : Controller
    {
        StockService stockService = new StockService();
        // GET: Stock
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StockList()
        {
            return View();
        }
        public ActionResult StockTransfer()
        {
            return View();
        }
        public ActionResult StockReportAction()
        {
            return View();
        }
        public ActionResult StockTransferReport()
        {
            return View();
        }
        
        [HttpPost]
        public FileResult StockTransfarReportCall(StockTransfarReportVM stockTransfarReportVM)
        {
            ReportViewer rptViewer = new ReportViewer();

            var data = stockService.TransfarProductList(stockTransfarReportVM);
            rptViewer.ProcessingMode = ProcessingMode.Local;
            rptViewer.LocalReport.ReportPath = Server.MapPath("~/RDLC/rptStockTransfarReport.rdlc");
            rptViewer.LocalReport.EnableExternalImages = true;
            rptViewer.LocalReport.DataSources.Add(new ReportDataSource("SPResults", data));
            rptViewer.LocalReport.Refresh();
            Warning[] warnings;
            string[] streamIds;
            string mimeType = string.Empty;
            string encoding = string.Empty;
            string extension = string.Empty;
            byte[] bytes = rptViewer.LocalReport.Render("PDF", null, out mimeType, out encoding, out extension, out streamIds, out warnings);
            return File(bytes, "application/pdf");
        }
       
    }
}

eShop.WebUI/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

eShop.WebUI/Views/Shared/_headerAuth.cshtml
<header id="header">
    <div id="logo-group">
        @*<span id="logo"> <img src="~/img/logo.png" alt="SmartAdmin"> </span>*@
    </div>
    @*<span id="extr-page-header-space"> <span class="hidden-mobile hidden-xs">Need an account?</span> <a href="register.html" class="btn btn-danger">Create account</a> </span>*@
</header>

eShop.WebUI/Views/Shared/_leftSide.cshtml
 <!-- #NAVIGATION -->
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS/SASS variables -->
<aside id="left-panel">

    <!-- User info -->
    <div class="login-info">
        <span>
            <!-- User image size is adjusted inside CSS, it should stay as is -->

            <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
                <img src="~/img/avatars/male.png" alt="me" class="online" />
                <span>
                    @User.Identity.Name.ToString();
                </span>
                <i class="fa fa-angle-down"></i>
            </a>
        </span>
    </div>
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive

    To make this navigation dynamic please make sure to link the node
    (the reference to the nav > ul) after page load. Or the navigation
    will not initialize.
    -->
    <nav>
        <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->
        @*@Html.Action("GetMenu", "Home")*@
        <ul>
            <li class="">
                <a href="@Url.Action("Index","Home")" title="Dashboard"><i class="fa fa-lg fa-fw fa-desktop"></i> <span class="menu-item-parent">Dashboard</span></a>
            </li>

            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-cogs"></i> <span class="menu-item-parent">Set Up</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("Branch","MasterSetUp")">Branch</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Color","MasterSetUp")">Color</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Size","MasterSetUp")">Size</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Brand","MasterSetUp")">Brand</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Category","MasterSetUp")">Category</a>
                    </li>
                    <li>
                        <a href="@Url.Action("UOM","MasterSetUp")">UOM</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SubCategory","MasterSetUp")">SubCategory</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Customer","MasterSetUp")">Customer</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Supplier","MasterSetUp")">Supplier</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Event_Discount","MasterSetUp")">Event/Offer</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa fa-dropbox"></i> <span class="menu-item-parent">Product</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("ProductAdd","Product")">Product Add</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Productlist","Product")">Product List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ProductSaveExcel","Product")">Bulk Product Upload</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ProductSearch","Product")">Product Report</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-shopping-cart"></i> <span class="menu-item-parent">Purchease</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("PurcheasePOS","Purchease")">Stock In</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Purcheaselist","Purchease")">Purchease List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("PurcheaseReturn","Purchease")">Purchease Return</a>
                    </li>
                    <li>
                        <a href="@Url.Action("PurcheaseReturnList","Purchease")">Purchease Return List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("PurcheaseReport","Purchease")">Purchease Report</a>
                    </li>


                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-shopping-bag"></i> <span class="menu-item-parent">Sales Invoice</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("SalesList","Sales")">Invoice List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SalesPOS","Sales")">SalesPOS</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SalesReturn","Sales")">Sales Return</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SalesReturnList","Sales")">Sales Return List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SalseReport","Sales")">Sales Report</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-line-chart"></i> <span class="menu-item-parent">Stock</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("StockList","Stock")">Stock List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("StockReportAction","Stock")">Stock Report</a>
                    </li>
                    <li>
                        <a href="@Url.Action("StockTransfer","Stock")">Stock Transfer</a>
                    </li>
                    <li>
                        <a href="@Url.Action("StockTransferReport","Stock")">Stock Transfer Report</a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-money"></i> <span class="menu-item-parent">Accounts</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("AccountRecive","Accounting")">Account Reciveable</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AccountPayable","Accounting")">Account Payable</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AccountCreate","Accounting")">Account Create</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AccountPayment","Accounting")">Payment</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AccountReceipt","Accounting")">Receipt</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AccountManagement","Accounting")">Management</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AccountRecivePayment","Accounting")">Account Receive Payment</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-users"></i> <span class="menu-item-parent">User Management</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("RolesList","Account")">Roles</a>
                    </li>
                    <li>
                        <a href="@Url.Action("UserCreate","Account")">User</a>
                    </li>

                </ul>
            </li>
            <li class="">
                <a href="@Url.Action("Organization","MasterSetUp")" title="Dashboard"><i class="fa fa-lg fa-fw fa-gear"></i> <span class="menu-item-parent">Business Profile</span></a>
            </li>
            @*<li>*@
            @*<a href="#"><i class="fa fa-lg fa-fw fa-wrench"></i> <span class="menu-item-parent">Stock</span></a>
            <ul>
                <li>
                    <a href="@Url.Action("Setting","MasterSetUp")">Setting</a>
                </li>
                x
            </ul>
        </li>*@
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu"> <i class="fa fa-arrow-circle-left hit"></i> </span>
</aside>
<!-- END NAVIGATION -->

eShop.WebUI/Views/Shared/_leftSideAuth.cshtml
<style>
    .col-centered {
        float: none;
        margin: 0 auto;
    }
</style>
<div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
    <h1 class="txt-color-red login-header-big col-centered"><img  src="~/img/logo-dark.png"  style="width: 340px;" /></h1>
    <div class="hero">
        <div class="pull-left login-desc-box-l">

            <img src="~/img/logPage.jpg" class="thumbnail" height="350"/>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <h5 class="about-heading">About Projukti ERP - Are you up to date?</h5>
            <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
            </p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <h5 class="about-heading">Not just your average template!</h5>
            <p>
                Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
            </p>
        </div>
    </div>

</div>